name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [created]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [Debug, RelWithDebInfo]
    steps:
      - uses: actions/checkout@v3

      # Bootstrap
      - name: Bootstrap deps (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: bash scripts/bootstrap.sh

      - name: Bootstrap deps (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\scripts\bootstrap.ps1 -UseVcpkg

      - name: Install lcov (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      # Configure & Build
      - name: Configure & Build (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: bash scripts/build.sh ${{ matrix.config }}

      - name: Configure & Build (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\scripts\build.ps1 -Config ${{ matrix.config }} '-DCMAKE_TOOLCHAIN_FILE=third_party/vcpkg/scripts/buildsystems/vcpkg.cmake'

      # Run tests
      - name: Run tests (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: bash scripts/tests.sh ${{ matrix.config }}
      
      - name: Dump test logs on failure
        if: failure()
        run: |
          echo "=== BEGIN TEST LOGS ==="
          for log in build/tests/*.log; do
            echo
            echo "----- $log -----"
            head -n 1000 "$log" || cat "$log"
            echo
          done
          echo "==== END TEST LOGS ===="

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\scripts\tests.ps1 -Config ${{ matrix.config }}

      - name: Dump test logs on failure
        if: failure()
        run: |
          echo "=== BEGIN TEST LOGS ==="
          Get-ChildItem build/tests/*.log | ForEach-Object {
            Write-Host "`n----- $($_.Name) -----"
            Get-Content $_.FullName -TotalCount 1000
          }
          echo "==== END TEST LOGS ===="

